// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwnnspkkxbwecaecdrgn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3bm5zcGtreGJ3ZWNhZWNkcmduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMjc1MjksImV4cCI6MjA3MDYwMzUyOX0.3UcIzRTz3tfN3h_POUhUJhgOn-VGX9J3Z_2rxELeX_s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});