// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybwokkvtqphjnzwcjcro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlid29ra3Z0cXBoam56d2NqY3JvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MDM3MzYsImV4cCI6MjA2NDA3OTczNn0.lByDjB8KzmvMw0P849FQfaeJW44vn-s80m4adpg4dBs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});